---
title: "Homework 1"
author: "YOU"
date: "add your date here"
output: html_document
---

**Remember: show your code!**

```{r}
# this is a comment inside of a code chunk. 
# you should use comments to explain what your code does
# You can use command + option + i  or ctrl + alt + i to generate a code chunk. 
# Click 'knit' above (or ctrl (cmd on mac) + shift + k) to see the html output file.

2 + 2

a<-4
b<-3

a^b
```


1. Read Chapter 2 of Kieran Healy's Data Visualization (available for free here: https://socviz.co/gettingstarted.html#gettingstarted)

2. Confirm you have the needed packages installed by loading the `tidyverse` package. Install (if needed) and load the `gapminder` package

Create a new code chunk with the hotkey ctrl (or cmd on mac) + shift + I, then load these libraries inside the chunk. 

3. Create a new variable in the tibble `gapminder` called `pop1000` that is equal to the population of a country in 1,000s of people (`pop/1000`).

Create a new code chunk with the hotkey ctrl (or cmd on mac) + shift + I, then write your code for this operation inside the chunk.

4. Compute the mean life expectancy for all observations in the dataset

5. Use the `unique()` function to list all of the countries with observations in the `gapminder` tibble. 

6. Create a scatterplot (using ggplot) showing `lifeExp` on the y axis and `gdpPercap` on the x axis. 

Provide a brief interpretation of your plot outside of the code chunk. Knit your document to confirm that it looks ok.

7. Reproduce the plot from 6, but instead, plot `log(gdpPercap)` on the x axis. Provide a brief interpretation of your plot.
