---
title: "HW12"
author: "Frank Edwards"
date: "`r Sys.Date()`"
output: html_document
---

1. Using IPUMS and the 2023 ACS (one year) sample, create a pull with the following variables: INCTOT (person level, income), EDUC (person level, education), RACE (person level, race, ethnicity, nativity), SEX (person level, demographic) and AGE (person level, demographic)

2. Explain in plain language a basic theory for how income is related to education, race, sex, and age. 

3. Write a regression equation to operationalize your theory explained in (2)

4. Estimate that regression model. Interpret the coefficients, describe whether estimates are statistically significant, and describe the precision of your estimates (as 95 percent confidence intervals for Beta estimates)

5. Estimate a second regression model using a different specification. Consider whether interactions may be appropriate. 

6. Use goodness of fit metrics (e.g. $R^2$) to compare these two models.

7. Visualize your findings by using predict to generate expected values. Interpret this visual with at least 3-4 sentences. 

8. Compare your visual in (7) to a scatterplot of the observed data. Note any discrepancies. Do you believe your model is a good approximation of the data generating process (i.e. the social processes that produce the measure INCOME we are using on the ACS)?

9. Tell me one thing you feel confident you understand now that you didn't understand at the beginning of the semester.