---
title: "HW2"
author: "YOUR NAME"
date: "9/15/26"
format: html
---

```{r, include = F}
library(tidyverse)
library(knitr)
```


# Math practice

We can write math equations in quarto using LaTeX syntax. It's funky but you'll get used to it.

We start and end an equation with two $ symbols like this

$$f(x) = x^2 + 3x$$ 

Provide equations in quarto LaTeX when appropriate.

Read ROS Chapter 3 with a cool math thing $x^2 + 80$

ROS Exercises 3.1, 3.2, 3.6, 3.7

## Question 3.1

```{r}
dat3.1 <- data.frame(age.grp = 
                       c("18-29", "30-44", 
                         "45-64", "65+"),
                     pct.taxes = c(0.5, 0.6, 0.4, 0.3),
                     pop = c(200, 250, 300, 250)
                     )

# dat3.1$pop.prop <- dat3.1$pop / sum(dat3.1$pop)

dat3.1 <- dat3.1 |>
  mutate(pop.prop = pop / sum(pop))

dat3.1 <- dat3.1 |> 
  mutate(wght.avg = pct.taxes * pop.prop)
  
# sum(dat3.1$wght.avg)

kable(dat3.1, caption = "my cool table")
```

The weighted average for population supporting the tax increase is `r sum(dat3.1$wght.avg) * 100`%


