---
title: "Homework 3"
date: "today?"
author: "Your name here"
output: html_document
---

## Part 1

Review chapter 5 of R for Data Science (https://r4ds.had.co.nz/transform.html)

These excersises use the `flights` data from `library(nycflights13)`

1. Use `filter()` to find all flights that

- Had an arrival delay of two or more hours
- Flew to Houston (IAH or HOU)
- Were operated by United, American, or Delta
- Departed in summer (July, August, and September)
- Arrived more than two hours late, but didn’t leave late
- Were delayed by at least an hour, but made up over 30 minutes in flight
- Departed between midnight and 6am (inclusive)

2. Use `arrange()` to sort flights to find the most delayed flights. Find the flights that left earliest.

3. Use mutate to compute with `arr_time - dep_time`. 

4. Use `group_by` and `summarise()` to compute the average departure delay by carrier

## Part 2

The STAR (Student-Teacher Achievement Ratio) Project is a four year
*longitudinal study* examining the effect of class size in early
grade levels on educational performance and personal
development. 

This exercise is in part based on:
 Mosteller, Frederick. 1997. “[The Tennessee Study of Class Size in the 
 Early School Grades.](http://dx.doi.org/10.2307/3824562)” *Bulletin of 
 the American Academy of Arts and Sciences* 50(7): 14-25.
  
A longitudinal study is one in which the same
participants are followed over time.  This particular study lasted
from 1985 to 1989 involved 11,601 students. During the four years of
the study, students were randomly assigned to small classes,
regular-sized classes, or regular-sized classes with an aid.  In all,
the experiment cost around $12 million. Even though the program
stopped in 1989 after the first kindergarten class in the program
finished third grade, collection of various measurements (e.g.,
performance on tests in eighth grade, overall high school GPA)
continued through the end of participants' high school attendance.

You may load the data in the qss library with `data(STAR)`

We will analyze just a portion of this data to investigate whether the small class sizes improved performance or not. The names and
descriptions of variables in this data set are:

--------------------------------------------------------------------------------
 Name                 Description
 -------------------- ----------------------------------------------------------
 `race`               Student's race (White = 1, Black = 2, Asian = 3, 
                      Hispanic = 4,  Native American = 5, Others = 6)
 
 `classtype`          Type of kindergarten class (small = 1, regular = 2, regular with aid = 3)
 
 `g4math`             Total scaled score for math portion of fourth grade standardized test 
 
 `g4reading`          Total scaled score for reading portion of fourth grade standardized test 
 
 `yearssmall`         Number of years in small classes 
 
 `hsgrad`             High school graduation (did graduate = 1, did not graduate = 0) 
 --------------------------------------------------------------------------------
 
Note that there are a fair amount of missing
values in this data set.  For example, missing values arise because
some students left a STAR school before third grade or did not enter a STAR school until first grade.

## Question 1

Create a new factor variable called `kinder` in the data
  frame.  This variable should recode `classtype` by changing
  integer values to their corresponding informative labels (e.g.,
  change 1 to `small` etc.).  Similarly, recode the
  `race` variable into a factor variable with four levels
  (`white`, `black`, `hispanic`, `others`) by
  combining Asians and Native Americans as the `others`
  category.  For the `race` variable, overwrite the original
  variable in the data frame rather than creating a new one.  Recall
  that `na.rm = TRUE` can be added to functions in order to
  remove missing data.
  
## Question 2

How does performance on fourth grade reading and math tests for
  those students assigned to a small class in kindergarten compare
  with those assigned to a regular-sized class?  Do students in the
  smaller classes perform better?  Use means to make this comparison
  while removing missing values.  Give a brief substantive
  interpretation of the results.  To understand the size of the
  estimated effects, compare them with the standard deviation of the
  test scores.
   
## Question 3

Instead of comparing just average scores of reading and math
  tests between those students assigned to small classes and those
  assigned to regular-sized classes, look at the entire range of
  possible scores.  To do so, compare a high score, defined as the
  66th percentile, and a low score (the 33rd percentile) for small
  classes with the corresponding score for regular classes.  These are
  examples of *quantile treatment effects*.  Does this analysis
  add anything to the analysis based on mean in the previous question?

## Question 4

Some students were in small classes for all four years that the
  STAR program ran. Others were assigned to small classes for only one
  year and had either regular classes or regular classes with an aid
  for the rest. How many such students of each type are in the data
  set?  Create a contingency table of proportions using the
  `kinder` and `yearsmall` variables.  Does participation
  in more years of small classes make a greater difference in test
  scores?  Compare the average and median reading and math test scores
  across students who spent different numbers of years in small
  classes.

## Question 5

We examine whether the STAR program reduced the achievement gaps
  across different racial groups.  Begin by comparing the average
  reading and math test scores between groups among those students who were assigned
  to regular classes with no aid.  Conduct the same comparison among
  those students who were assigned to small classes.  Give a brief
  substantive interpretation of the results of your analysis.
  
## Question 6

We consider the long term effects of kindergarden class size.
  Compare high school graduation rates across students assigned to
  different class types.  Also, examine whether graduation rates
  differ by the number of years spent in small classses.  Finally, as
  done in the previous question, investigate whether the STAR program
  has reduced the racial gap between white and minority students'
  graduation rates.  Briefly discuss the results.