---
title: "HW 5"
author: "Your name here"
date: "today"
output: html_document
---

Read Chapter 3 from Wickham's R for Data Science (https://r4ds.had.co.nz/data-visualisation.html). Try the practice exercises to familiarize yourself with `ggplot()` basics.

```{r message= F}
library(tidyverse)
```

This assignment uses the data `iris`. It is built into `tidyverse` and is loaded when you run `library(tidyverse)`.

1. Summarize the characteristics of the `iris` data frame in any way you think is appropriate.z

2. Create separate data frames for each species of iris in the data.

3. Provide a histogram of `Sepal.Length` using `ggplot` for each of these new data frames

4. Provide a histogram of `Sepal.Length` using the original iris data frame

5. Provide a histogram of `Sepal.Length` using the original iris data frame. Include faceting by `Species`

6. Provide a scatterplot of `Sepal.Length` by `Sepal.Width`

7. Provide a scatterplot of `Sepal.Length` by `Sepal.Width`. Include faceting by `Species`

8. Provide a boxplot of `Petal.Length` by `Species`

9. Compute the average value of each sepal and petal variable by species

10. Compute the standard deviation of each sepal and petal variable by species

11. How many flowers had a `Petal.Length` above the average `Petal.Length`?