---
title: "HW 6"
author: "YOU"
date: "Date"
output: html_document
---

In 2002, the World Health Organization conducted a survey of two provinces in China and three provinces in Mexico. This
exercise is based on: 

> Gary King, Christopher J. L. Murray, Joshua A. Salomon, and Ajay Tandon. (2004). '[Enhancing the Validity and Cross-Cultural Comparability of Measurement in Survey Research.]( https://doi.org/10.1017/S000305540400108X)' *American Political Science Review*, 98:1 (February), pp.191-207.
  
In this exercise we analyze respondents' views on their own political efficacy.  First, the following self-assessment question was asked.

>  How much say do you have in getting the government to address issues that interest you?
>
>  (5) Unlimited say, (4) A lot of say, (3) Some say, (2) Little say, (1) No say at all.

After the self-assessment question, three vignette questions were asked.

>  [Alison] lacks clean drinking water. She and her neighbors are supporting an opposition candidate in the forthcoming elections that has promised to address the issue. It appears that so many people in her area feel the same way that the opposition candidate will defeat the incumbent representative.
>
>  [Jane] lacks clean drinking water because the government is pursuing an industrial development plan. In the campaign for an upcoming election, an opposition party has promised to address the issue, but she feels it would be futile to vote for the opposition since the government is certain to win.
>
>  [Moses] lacks clean drinking water. He would like to change this, but he can't vote, and feels that no one in the government cares about this issue. So he suffers in silence, hoping something will be done in the future.

The respondent was asked to assess each vignette in the same manner as the self-assessment question.

>  How much say does ['name'] in getting the government to address issues that interest [him/her]?
>
>  (5) Unlimited say, (4) A lot of say, (3) Some say, (2) Little say, (1) No say at all.

where ['name'] was replaced with either Alison, Jane, or Moses.

The data set we analyze `vignettes.csv` contains the following variables:

-------------------------------------------------------------------------------
 Name                 Description
 -------------------- ---------------------------------------------------------
 `self`               Self-assessment response 
 
 `alison`             Response on Alison vignette 
 
 `jane`               Response on Jane vignette 
 
 `moses`              Response on Moses vignette
 
 `china`              1 for China and 0 for Mexico  
 
 `age`                 Age of respondent in years 
------------------------------------------------------------------------------

In the analysis that follows, we assume that these survey responses can be treated as numerical values.  For example, `Unlimited say` = 5, and `Little say` = 2.   This approach is not appropriate if, for example, the difference between `Unlimited say` and `A lot of say` is  not the same as the difference between `Little say` and `No say at all`.  However, relaxing this assumption is beyond the scope of this chapter.

```{r}
#load the data
library(tidyverse)

dat<-read_csv("https://raw.githubusercontent.com/kosukeimai/qss/master/MEASUREMENT/vignettes.csv")
```


## Question 1

We begin by analyzing the self-assessment question.  Plot the distribution of responses separately for China and Mexico using barplots, where the vertical axis is the proportion of respondents. In addition, compute the mean response for each country.  Which country's respondents seem to have a higher degree of political efficacy?  Does this seem plausible when Mexican citizens voted out out the Institutional Revolutionary Party (PRI)  after more than 70 years or rule and Chinese citizens have not been able to vote in a fair election to date?

## Question 2

We examine the possibility that any difference in the levels of efficacy between Mexican and Chinese respondents is due to the difference in their age distributions.  Create histograms for the age variable separately for Mexican and Chinese respondents. Examine the mean value for each country. Examine the standard deviation for each country. What differences in age distribution do you observe between the two countries?  

## Question 3

One problem of the self-assessment question is that survey respondents may interpret the question differently.  For example, two respondents who choose the same response category may be facing quite different political situations and hence may interpret `A lot of say`  differently.  To address this problem, we rank a respondent's answer to the self-assessment question relative to the same respondent's answer to a vignette question.  Compute the proportion of respondents, again separately for China and Mexico, who ranks themselves (according to the self-assessment question) as
having less say in the government's decisions than Moses (the last vignette).  How does the result of this analysis differ from that of the previous analysis?  Give a brief interpretation of the result.
  
## Question 4
  
Restrict the data to survey respondents who ranked these three vignettes in the expected order (i.e., `Alison` $\ge$ `Jane` $\ge$ `Moses`).  Now create a variable that represents how respondents rank themselves relative to each vignette.  This variable should be equal to 1 if a respondent ranks themself lower than `Moses`, 2 if ranked the same as `Moses` or higher than `Moses` but lower than `Jane`, 3 if ranked the same as `Jane` or higher than `Jane` but lower than `Alison`, and 4 if ranked as high as `Alison` or higher.  Create barplots of this new variable as in Question 1. Also, compute the mean value of this new variable separately for China and Mexico.  Give a brief interpretation of the result by comparing
these results with those obtained in Question 1.

## Question 5

Is the problem identified above more or less severe among older respondents when compared to younger ones?  Consider the previous question for those who are 40 years or older and those who are younger than 40 years.  Do your conclusions between these  two groups of respondents? Relate your discussion to your finding for Question 2.

