---
title: "HW5"
author: "Frank Edwards"
date: "`r Sys.Date()`"
output: html_document
---

Use the UCR 2022 Arrests by Age, Sex, and Race data for this assignment. You will need to refer to the included codebook for this assignment. 

```{r}
dat<-read_tsv("./data/ICPSR_39063/DS0002/39063-0002-Data.tsv")
```

1. Load the 12-month data into R using the `read_tsv` command

2. Use select() to create a new data frame that includes only the following variables: `STATE`, `AGENCY`, `POP`, `OFFENSE`, `M25_29`, `F25_29`

3. Using the codebook, identify the cases with missing values on the focal variables. Use filter() to remove rows with missing values from your data frame.

4. Use filter() to subset the data frame you created to only include the offense category 'Murder and non-negligent manslaughter'

5. Create two new variables that measure Male age 25-29 arrests per 100,000 population, and Female age 25-29 arrests per 100,000 population. 

6. Create histograms for each of these two per capita arrest measures. Interpret the histograms

7. Repeat these histograms, but subset to only those places with greater than 10,000 population. Interpret the histograms.

8. Scatterplot your two per capita arrest measures. Interpret this scatterplot.

9. Subset to only places with a population larger than 10,000, repeat the scatterplot, and interpret. 

10. Compute the correlation between your per capita measures and interpret, using insights from the histograms and scatterplots. 

11. Compute the mean of the agency-level arrest rates for Male arrests by state. Plot the distribution of these means. 

12. Compute a 95 percent confidence interval for average agency-level Male arrests rates by state. What does this interval mean? 

13. Does the central limit theorem apply here? Why or why not? How should that impact our interpretation of the confidence interval above? 