---
title: "HW8"
author: "Frank Edwards"
output: html_document
---

In this homework, we'll practice fitting a variety of linear regression models.

## Question 1

For this question, use the `mtcars` data built into R. This data displays a series of measures on cars from 1974. Run `?mtcars` to see the codebook.

1. Create a scatterplot of miles per gallon (`mpg`) and vehicle weight (`wt`). Interpret the scatterplot. Do you think this might be a good candidate for a linear model?

2. Estimate a linear regression model with `mpg` as the outcome and `wt` as a predictor. Interpret the intercept and slope coefficients.

3. What does your model tell you substantively (real world implications) about this relationship?

## Question 2

For this question, we will use the `USArrests` data buit into R

1. Create a scatterplot of the relationship between homicide arrest rates and the proportion of the state that lives in cities (`UrbanPop`). Compute a correlation coefficient. Interpret your plot and correlation estimate.

2. Estimate a linear regression with `Murder` as the outcome and `UrbanPop` as a predictor. Interpret the coefficients.

3. What does your model tell you substantively about the relationship between state urban population composition and homicide arrest rates? 

## Question 3

For this question we will use the `gapminder` data. You will need to install and load the `gapminder` package. Check the documentation with `?gapminder`

1. Scatterplot the relationship between `gdpPercap` and `lifeExp`. Interpret.

2. Estimate a linear regression with `lifeExp` as an outcome and `gdpPercap` as a predictor. Interpret.

3. Now, scatterplot the relationship between the logarithm of GDP per capita and life expectancy. Interpret.

4. Estimate a linear regerssion with life expectancy as an outcome and log(GPD per capita) as a predictor. Interpret. 

5. Briefly explain the differences in how you should interpret the slope coefficient in model 2 compared to model 4. 

Hint: if you are having trouble thinking about logarithms, try this code and think about how log(x) is related to x

```{r}
x<-1:1000
plot(x, log(x))
```

