---
title: "Homework 8"
author: "YOUR NAME HERE"
date: "SUBMISSION DATE HERE"
output:
  html_document: default
---

In this exercise, we analyze the causal effects of a criminal record on the job prospects of white and black job applicants. This exercise is based on: 

Pager, Devah. (2003). "[The Mark of a Criminal Record](https://doi.org/10.1086/374403)." *American Journal of Sociology* 108(5):937-975. You are also welcome to watch Professor Pager discuss the design and result [here](https://youtu.be/nUZqvsF_Wt0).

To isolate the causal effect of a criminal record for black and white applicants, Pager ran an audit experiment. In this type of experiment, researchers present two similar people that differ only according to one trait thought to be the source of discrimination. This approach was used in the resume experiment described in Chapter 2 of *QSS*, where researchers randomly assigned stereotypically African-American-sounding names and stereotypically white-sounding names to otherwise identical resumes to measure discrimination in the labor market.

To examine the role of a criminal record, Pager hired a pair of white men and a pair of black men and instructed them to apply for existing entry-level jobs in the city of Milwaukee. The men in each pair were matched on a number of dimensions, including physical appearance and self-presentation. As much as possible, the only difference between the two was that Pager randomly varied which individual in the pair would indicate to potential employers that he had a criminal record. Further, each week, the pair alternated which applicant would present himself as an ex-felon. To determine how incarceration and race influence employment chances, she compared callback rates among applicants with and without a criminal background and calculated how those callback rates varied by race.

In the data you will use `criminalrecord.csv` nearly all these cases are present, but 4 cases have been redacted. As a result, your findings may differ slightly from those in the paper. The names and descriptions of variables are shown below. You may not need to use all of these variables for this activity. We’ve kept these unnecessary variables in the dataset because it is common to receive a dataset with much more information than you need.


------------------------------------------------------------------------------------------
Name                        Description
--------------------------- --------------------------------------------------------------
`jobid`                     Job ID number  

`callback`                  1 if tester received a callback, 0 if the tester did not receive a callback. 

`black`                     1 if the tester is black, 0 if the tester is white.

`crimrec`                   1 if the tester has a criminal record, 0 if the tester does not.

`interact`                  1 if tester interacted with employer during the job application, 0 if tester does not interact with employer.
`city`                      1 is job is located in the city center, 0 if job is located in the suburbs.

`distance`                  Job’s average distance to downtown.

`custserv`                  1 if job is in the costumer service sector, 0 if it is not.

`manualskill`               1 if job requires manual skills, 0 if it does not.

------------------------------------------------------------------------------------------

```{r include = F}
### load needed packages
library(tidyverse)
### read in data from course website
dat<-read.csv("https://raw.githubusercontent.com/f-edwards/intro_stats/master/data/criminalrecord.csv")
```


## Question 1  

Estimate a linear regression model with `callback` as the outcome and `crimrec` as the predictor. 

- Write the model mathematically.

- Interpret the substantive meaning of the slope coefficient and intercept coefficient.


## Question 2  

Estimate a linear regression model with `callback` as the outcome and `black` as the predictor.

- Write the model mathematically.

- Interpret the substantive meaning of the slope coefficient and intercept coefficient.

## Question 3

Estimate a linear regression with `callback` as the outcome, and `black` and `crimrec` as predictors.

- Write the model mathematically

- Interpret the substantive meaning of the slope and intercept coefficients

## Question 4

Estimate a linear regression with `callback` as the outcome, and an interaction of `black` and `crimrec` as predictors.

- Write the model mathematically

- Interpret the substantive meaning of the slope and intercept coefficients

- Compare your results in question 3 and question 4. Explain any differences.

## Question 4

Using your model from question 3, compute expected callback rates for all groups and complete the table below (just fill in the blank spaces, it will render when you knit)


|        | Criminal record  | No record   |
|---     |---               |---          |
| Black  |                  |             |
| White  |                  |             |

Interpret these findings.


## Question 5

Compare the results in question 4 to the results you obtained in homework 2. What can you say about the relationship between the expected values produced by your regression and your results from homework 2. Think about the relationship between *expected values* and *observed means*. 
