---
title: "Mid-semester assessment: Intro Statistics"
output: pdf_document
---

1. What are 3 concepts or techniques you are struggling with so far this semester?

\vspace{1.5in}

2. What are 3 concepts or techniques you feel like you've improved on so far this semester?

\vspace{1.5in}

3. What parts of the course do you think are not working well?

\vspace{1.5in}

4. What parts of the course do you think are working well? 

\vspace{1.5in}

5. What could we do differently to improve your learning?

\newpage

## Programming assessment

All questions below use the following data. Write R commands that will provide the desired results. The data.frame is named iris.


```{r echo = FALSE}
dat<-iris[c(1:3,51:53, 101:103), ]
row.names(dat)<-NULL
library(pander)
pander(dat)
```

1. Calculate the ratio of the average sepal length to the average petal length for all of the observations.

\vspace{1in}

2. Calculate the average petal width for each species separately

\vspace{1in}

3. Use ggplot to provide a scatterplot of sepal length against sepal width. Make sensible choices to help to visualize the relationship

\vspace{1.5in}

4. Estimate a linear regression model for the relationship between sepal length  and sepal width. Sepal length should be your outcome variable.

\vspace{1in}

5. What is the probability that a randomly chosen observation will be of species Versicolor? You can do this one without R.